M48
; DRILL file {KiCad 9.0.4} date 2025-09-18T09:53:16-0700
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-09-18T09:53:16-07:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.4
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.600
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C1.800
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C3.000
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T4C6.528
%
G90
G05
T1
X147.32Y-88.9
T2
X147.32Y-93.4
T3
X229.616Y-95.25
X229.616Y-107.95
T4
X133.35Y-88.9
X133.35Y-114.3
X234.95Y-88.9
X234.95Y-114.3
M30
